In [2]:
import numpy as np

y_pred = np.zeros(10000)
y_test = np.zeros(10000)

indices1 = np.random.randint(0, 10000, 300)
indices2 = np.random.randint(0, 10000, 400)
indices3 = np.random.randint(0, 10000, 500)

y_pred[indices1] = 1
y_test[indices2] = 1
y_pred[indices3] = 1
y_test[indices3] = 1

In [3]:
np.sum(y_test)

857.0

In [4]:
np.sum(y_pred)

766.0

In [5]:
from sklearn.metrics import accuracy_score
print("Accuracy score: ", accuracy_score(y_test, y_pred))


Accuracy score:  0.9363


In [6]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[8870,  273],
       [ 364,  493]], dtype=int64)

In [7]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.96      0.97      0.97      9143
         1.0       0.64      0.58      0.61       857

    accuracy                           0.94     10000
   macro avg       0.80      0.77      0.79     10000
weighted avg       0.93      0.94      0.93     10000



In [8]:
from sklearn.metrics import precision_recall_curve
precision, recall, thresholds = precision_recall_curve(y_test, y_pred)

In [9]:
precision


array([0.0857    , 0.64360313, 1.        ])

In [10]:
recall

array([1.        , 0.57526254, 0.        ])

In [11]:
thresholds

array([0., 1.])